# Generated by Django 5.1.6 on 2025-02-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='air_quality',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sunrise',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sunset',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
