# Generated by Django 5.1.6 on 2025-02-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherdata_wind_deg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='wind_direction',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='hourly_temperatures',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='air_quality',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='sunset',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
