# Generated by Django 5.1.6 on 2025-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_weatherdata_wind_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='air_quality',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='hourly_temperatures',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='sunset',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='wind_deg',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='icon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
