# Generated by Django 5.1.6 on 2025-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_weatherdata_air_quality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
