# Generated by Django 5.1.6 on 2025-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_savedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlocation',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='icon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
